# Generated by Django 2.0.7 on 2018-07-10 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('battery_status', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
