# Generated by Django 2.0.7 on 2018-07-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='device_id',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
