# Generated by Django 2.0.7 on 2018-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180710_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='device_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
