# Generated by Django 2.0.7 on 2018-07-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180710_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelist',
            name='device_id',
        ),
    ]
