# Generated by Django 2.0.7 on 2018-07-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_devicelist_device_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceList',
            new_name='Device',
        ),
    ]
